steps:
  - name: gcr.io/cloud-builders/docker
    args: [ build, -t, gcr.io/$PROJECT_ID/oscbot, . ]

  - name: gcr.io/cloud-builders/gcloud
    args: [ compute, instance-groups, managed, rolling-action, restart, oscbot-group, --zone=us-east1-b ]

  images:
    - gcr.io/$PROJECT_ID/oscbot
